"""change models Users

Revision ID: f70d84313dee
Revises: 0d694d92a784
Create Date: 2026-01-25 21:05:08.620965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70d84313dee'
down_revision: Union[str, Sequence[str], None] = '0d694d92a784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
